services:
  mongodb:
    image: mongo:7
    container_name: chitchat-mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=chitchat
    volumes:
      - mongodb_data:/data/db
    restart: always

  redis:
    image: redis:7-alpine
    container_name: chitchat-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: always

  server:
    build: ./apps/server
    container_name: chitchat-server
    ports:
      - "8000:8000"
    env_file:
      - ./apps/server/.env
    depends_on:
      - mongodb
      - redis
    restart: always

  web:
    build: ./apps/web
    container_name: chitchat-web
    ports:
      - "5173:5173"
    environment:
      - VITE_BE_URL=http://localhost:8000
    depends_on:
      - server
    restart: always

volumes:
  mongodb_data:
  redis_data:
